### PR TITLE
let Machine.add_states() take **kwargs

### PR DESCRIPTION
**Pull request by Synss**
This can be useful for state mixins, see also Issue #229.

—as discussed.

Tested with:

```
from transitions import Machine
from transitions.extensions.states import add_state_features, Timeout

import time


@add_state_features(Timeout)
class CustomMachine(Machine):
    pass


class Model(object):

    def timeout(self):
        print("Timeout!")
        self.to_A()

model = Model()

states = ['A',
          {'name': 'B', 'timeout': 0.3, 'on_timeout': 'timeout'},
          {'name': 'C', 'timeout': 0.9, 'on_timeout': model.timeout}]

m = CustomMachine(model, states=states, initial='A')
model.to_B()
time.sleep(1)  # >>> "Timeout!"
print model.state  # >>>  'A'


def hello():
    print("hello")


m.add_state("bob", timeout=0.5, on_timeout=hello)
model.to_bob()
time.sleep(1)

```

### CODE REVIEW

**Comment by aleneum** [comment]
weird, the build [fails](https://travis-ci.org/pytransitions/transitions/builds/252929364) for python 2.7 and python 3.3 due to a recursion errors in `dill`. I cannot reproduce this with `tox` though 😕 .

**Comment by Synss** [comment]
interesting... that triggered an infinite recursion... I'll see if I can reproduce that.

**Comment by aleneum** [comment]
Maybe this is a one time phenomena... Could you extend the `add_states` docstring to cover the new parameter? This will not change the actual code but a) it's a nice thing to do anyway and b) it will trick travis into building again.

**Comment by aleneum** [comment]
Well... this [did not help](https://travis-ci.org/pytransitions/transitions/builds/252961932) (bummer). Maybe [this issue](https://stackoverflow.com/questions/44981303/python-dill-0-2-7-throwing-max-recursion-depth-exceeded-error) with dill 0.2.7 is related to what we experience. However, I also installed dill 0.2.7 and manually added `**kwargs` to `add_states` but everything works fine...

**Comment by Synss** [comment]
Yes, I have seen that. I will see if I can reproduce this tomorrow...

**Comment by aleneum** [comment]
I just rebuilt the 'state-extension' branch and (as expected) it [breaks too](https://travis-ci.org/pytransitions/transitions/builds/250291251) now ⛈ .

**Pull request merged**
