### PR TITLE
Add transition queue for each model in AsyncMachine

### PR DESCRIPTION
**Pull request by jekel**
Main purpose for separate queue for each model is to make them executed in parallel, and not sequential for all triggers from all models common queue  
Otherwise if some state in one models needs many time to be processed - all others will wait, and if that model triggers state to another - that trigger will be queued and can be executed more later, after all others triggers from another models execute
thats isn't quite right
Also, in case of exception inside transition - queue is cleared not for all machine, but only for model where exception was raised

### CODE REVIEW

**Comment by aleneum** [comment]
Hello @jekel,

an interesting and reasonable addition. Let's say we want to keep the current behaviour as the default behaviour but enable your workflow as well. As a developer, would you prefere another parameter such as  `AsyncMachine(queued=True, parallel_queue=True)` or another value for `queued` such as `AsyncMachine(queued='parallel')`.

**Comment by jekel** [comment]
Hello
I think you are right, that it would be better to make new behaviour as option `queued='model'`, and later after it will be test by more people - make it default.
I will make commit with changes

**Comment by aleneum** [comment]
Hi @jekel,

> I will make commit with changes

I already prepared some adjustments and waited for your feedback. So no need for adaptions from your side. I think I will be able to merge the PR today and release a new version today or tomorrow. Again, thank you for your contribution. It's always nice when an idea/suggestion is submitted so well prepared and outlined!

**Comment by jekel** [comment]
@aleneum i have another idea - when `remove_model` is called on machine, we need also to clear all queues and stop processing all transitions from removed model - what do you think about it? but it could be done only when we have separate queue for each model..

**Comment by aleneum** [comment]
> when remove_model is called on machine, we need also to clear all queues and stop processing all transitions from removed model

Good point. I'll see what can be done about it and will let you know.

**Comment by aleneum** [comment]
just a short update: i wrote some tests (which i didnt account for in my previous optimistic time estimation) for the 'model' queue mode and also added some documentation. removing queued events (from a single queue) is a bit more complicated than expected.I'll keep you updated.

**Comment by jekel** [comment]
Yeah.. its a good question how to clean queue..
I think, that the best way is to replace it with new - filtered by rule - model class is not the model to be removed

**Comment by aleneum** [comment]
The filtering itself is actually quite straight forward

```python
    def remove_model(self, model):
        models = listify(model)

        for mod in models:
            self.models.remove(mod)
            if self.has_queue == 'model':
                del self._transition_queue[mod]
            elif self.has_queue:
                self._transition_queue[mod] = deque([e for e in self._transition_queue if e.args[0] != mod])
```

but the processing in `Machine._process` does not expect the queue to be changed.

**Comment by aleneum** [comment]
I merged your changes into `feature-model-queues` (see [diff](https://github.com/pytransitions/transitions/compare/master...feature-model-queues)) but had to take another approach with a `dict` rather than a `defaultdict`. In #475, empty dictionary keys (with empty lists) caused quite some memory leak when models were constantly added and removed. This is why I think explicitly adding and removing dictionary keys with `deque` or `self._transitions_queue` is a better solution. Alternatively, one could use `defaultdict` but remove a key whenever a list is empty. That, however, has probably some considerable performance impact.
Furthermore, I struggled a bit with writing useful tests for using and removing model queues.

What's your oppinion about `dict` instead of `defaultdict`? Could you think of more streamlined tests for `test_model_queue` and `test_queued_remove`?

**Comment by aleneum** [comment]
hmm... removing_model still does not work as intended. wont work with more than one model left in the list and also result in multiple event queues

**Comment by jekel** [comment]
So...
first of all, if there is only one way to work with queues - from inside, i'm ok that list is created and destroyed from Machine explicitly -> `dict` is fine

another thing, in your code, you assume that `remove_model` is called from inside running transition,  
[here](https://github.com/pytransitions/transitions/compare/master...feature-model-queues#diff-938de46e643ab091cff6a7c23e4e752e8907e2266f47889d988923352f7a1058R650) and [here](https://github.com/pytransitions/transitions/compare/master...feature-model-queues#diff-6886dfaede3b127f0d73b71c33a7f6b19ce43c3d65bd443d40e7bec3fe5ecf06R612)  
so i think there will be exception when `remove_model` will be called when queue is empty.

like in my case -> model is removed from outside and there can be no running transitions

**Comment by aleneum** [comment]
>  so i think there will be exception when remove_model will be called when queue is empty.
right, need to add this to the tests

I implemented a `_DictionaryMock` which ignores keys and always returns `self._transitions_queue`. This way, handling of model queues and single queue can be kept similar.

**Comment by aleneum** [comment]
resolved in #492

**Pull request closed without merging**
