### PR TITLE
Avoid repeatedly appending [internal] to labels when generating graphs.

### PR DESCRIPTION
**Pull request by EvanKrall**

### CODE REVIEW

**Comment by aleneum** [comment]
Hello @EvanKrall, 

sorry for keeping you waiting so long. Editing the edge label directly is indeed a bad idea. It is not just repeatedly adding '[internal]' to internal transitions but also adding it to all non-internal edges after it:

```python
transitions = [['go', 'A', 'B'],
               dict(trigger='fail', source='A', dest=None, conditions=['failed']),
               dict(trigger='fail', source='A', dest='B', unless=['failed'])]
``` 
Result:

tst

Adding a temporal variable seems a reasonable workaround. I will merge this. Thank you for your contribution.

**Comment by intrinseca** [comment]
Hi, I'm encountering this issue as well, do you know when it will make it into a release?

**Comment by aleneum** [comment]
Hi @EvanKrall,

I will release 0.7 today or next Monday. It should be fixed but I want to test it with another configuration to make sure it tackles most corner cases. Could your provide a minimal configuration (2-3 states, transitions, conditions (just the names)) for me to add to the unit test?

**Comment by aleneum** [comment]
Hi @intrinseca,

I will release 0.7 today or next Monday. It should be fixed but I want to test it with another configuration to make sure it tackles most corner cases. Could your provide a minimal configuration (2-3 states, transitions, conditions (just the names)) for me to add to the unit test?

**Comment by intrinseca** [comment]
Here is an example - I haven't tested this with the development code but its showing the bug in the released version. I have included some transitions based on the `polled` event that are like the ones in my real code.

state_machine_graph


```
from transitions.extensions import GraphMachine as Machine


class Box:
    def door_closed(self):
        return True


if __name__ == "__main__":
    states = [
        "initial",
        "ready",
        "running"
    ]

    transitions = [
        ["booted", "initial", "ready"],
        {"trigger": "polled", "source": "ready", "dest": "running", "conditions": "door_closed"},
        ["done", "running", "ready"],
        ["polled", "*", None]
    ]

    machine = Machine(model=Box(),
                      states=states,
                      transitions=transitions,
                      show_conditions=True,
                      auto_transitions=False)

    machine.get_graph().draw("state_machine_graph.png", prog="dot")```

**Comment by aleneum** [comment]
Hi @intrinseca,

thank you for the fast response. I ran the following code:

```python
from transitions.extensions.diagrams import GraphMachine as Machine

states = [
    "initial",
    "ready",
    "running"
]

transitions = [
    ["booted", "initial", "ready"],
    {"trigger": "polled", "source": "ready", "dest": "running", "conditions": "door_closed"},
    ["done", "running", "ready"],
    ["polled", "*", None]
]

machine = Machine(states=states,
                  transitions=transitions,
                  show_conditions=True,
                  auto_transitions=False)

machine.get_graph().draw("state_machine_graph.png", prog="dot")
```

And got the following result with `master` (pre-release 0.7.0):

state_machine_graph

With `pygraphviz` (currently the default graphviz engine) as well as `graphziv` (will be used when you pass the parameter `use_pygraphviz=False` to `GraphMachine`). I will add your example to the graph test cases. Thanks again!

**Pull request merged**
