### PR TITLE
Generate methods may_<trigger> for check possible transition

### PR DESCRIPTION
**Pull request by artofhuman**
Ref #549

Hi, @aleneum. I create PR with feature `object.may_<trigger_name>` based on your sugeestion in the issue.

### CODE REVIEW

**Comment by broglep-work** [comment]
We gave this PR a try and it does not seem to work with nested state machines

**Comment by aleneum** [comment]
Hello @broglep-work,

thanks for the info. FYI: I will be back working on transitions after 15th of November.

**Comment by artofhuman** [comment]
I've added this feature for nested states + more tests. I've never used `prepare` callbacks before as well. I'll try to check this too.

**Comment by aleneum** [comment]
I merged your changes into the dev branch for 0.9 and added nested and async versions to the related machines. The tests pass so far. If you have some further test cases to integrated, let me know.

**Pull request merged**
