### PR TITLE
Nested enums now translate to nested states

### LINKED ISSUE #404: Support for nested states from nested Enums
Consider the following Enum:
```python
from enum import Enum, auto
class Foo(Enum):
  A = auto()
  B = auto()

class Bar(Enum):
  FOO = Foo
  C = auto()
```

If we were to provide `Bar` to a `HierarchicalMachine` I'd expect it to take all the items in Foo as children of the Foo state.

However this is not the case:
```
In[18]: from transitions.extensions import HierarchicalMachine
In[19]: HierarchicalMachine(states=Bar)
Out[19]: <transitions.extensions.nesting.HierarchicalMachine at 0x7f517ea75d90>
In[20]: machine = HierarchicalMachine(states=Bar)
In[21]: machine.states
Out[21]: 
OrderedDict([('FOO', <NestedState('FOO')@139987994034720>),
             ('C', <NestedState('C')@139987994035296>),
             ('initial', <NestedState('initial')@139987994035200>)])
In[22]: machine.states['FOO']
Out[22]: <NestedState('FOO')@139987994034720>
In[23]: machine.states['FOO'].states
Out[23]: OrderedDict()
```

This can be easily added if I am not wrong.

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #404.

This needs documentation but I don't know which version this feature will released on.
I'm assuming 0.9.0. Am I correct?

### CODE REVIEW

**Comment by aleneum** [comment]
That looks good to me. Some minor tweeks need to be done though (for instance [here](https://github.com/pytransitions/transitions/blob/070b45047a7d9c253401a39086b0f1ccc5b8dfc4/transitions/extensions/nesting.py#L28)). Did you check whether the resulting Graphviz graphs look okay? Is it possible to determine the actual state and can you use auto transitions?:

```python
from enum import Enum, auto
class Foo(Enum):
  A = auto()  # 1 
  B = auto()  # 2

class Bar(Enum):
  FOO = Foo
  C = auto()  # 1

m = HierarchicalMachine(states=Bar, initial=Bar.C)
m.to_FOO_A()  # does this work?
assert m.is_C() is False  # a check by state.value would return True though 
```

**Comment by thedrow** [comment]
Do we need to remove this check?
https://github.com/pytransitions/transitions/blob/070b45047a7d9c253401a39086b0f1ccc5b8dfc4/transitions/extensions/nesting.py#L27-L28

**Comment by thedrow** [comment]
Setting the initial to `Bar.C` uncovered a bug in this PR that causes the test to fail because of the Graphvis extension.
I fixed it now. I'll generate a graph and see if it looks correct.

**Comment by thedrow** [comment]
Looks right to me :)
g

**Comment by aleneum** [comment]
Merged! Thanks again for your valuable contributions!

> Setting the initial to Bar.C uncovered a bug in this PR that causes the test to fail because of the Graphvis extension.

this is comparable to #400 and should be fixed with 0a66a36. An additional test in `set_node_style` should not be necessary anymore. I removed it.

Sidenote: Enums with identical values cannot be distinguished. That should be at least mentioned in the documentation.

**Comment by thedrow** [comment]
> Do we need to remove this check?
> 
> https://github.com/pytransitions/transitions/blob/070b45047a7d9c253401a39086b0f1ccc5b8dfc4/transitions/extensions/nesting.py#L27-L28

Wait, what about this?

**Pull request merged**
